# -*- coding: utf-8 -*-
"""fig_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nh6gN7o8s86XgMQYDc9tM-kkvkEOX_mM
"""

# figures/fig_pipeline.py

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


def create_pipeline_figure(save_path):
    plt.rcParams.update({
        'font.family': 'serif',
        'mathtext.fontset': 'stix',
        'font.size': 9
    })

    fig, ax = plt.subplots(figsize=(7.2, 2.79))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 3)
    ax.axis('off')

    steps = [
        (0.1,  0.65, 1.55, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'Across\nDialogue\nDomains',
         '5 corpora (KO, EN)'),
        (1.95, 0.65, 1.55, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'LaBSE\nencoding',
         '768-dim utterances'),
        (3.8,  0.65, 1.55, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'Session-level\nPCA',
         '2D per session'),
        (5.65, 0.55, 1.9,  1.9,
         '#C5EAD8', '#1E7A4E', 1.5,
         'Lévy-area\ncomputation',
         r'$\mathrm{LA}(w)='
         r'\frac{1}{2}\sum_i'
         r'(x_i\Delta y_i-y_i\Delta x_i)$'),
        (7.85, 0.65, 2.05, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'Archetype\ndiscovery',
         r'$k=4$, silhouette $=.400$'),
    ]

    for (x, y, w, h, fc, ec, lw,
         title, sub) in steps:
        ax.add_patch(mpatches.FancyBboxPatch(
            (x, y), w, h,
            boxstyle="round,pad=0.06",
            fc=fc, ec=ec, lw=lw, zorder=2))
        ax.text(x + w / 2, y + h * 0.63,
                title,
                ha='center', va='center',
                fontsize=8.5, fontweight='bold',
                color='#222222', zorder=3,
                multialignment='center')
        ax.text(x + w / 2, y + h * 0.24,
                sub,
                ha='center', va='center',
                fontsize=7, color='#555555',
                style='italic', zorder=3)

    for xa in [1.65, 3.5, 5.35, 7.55]:
        ax.annotate(
            '', xy=(xa + 0.25, 1.5),
            xytext=(xa, 1.5),
            arrowprops=dict(
                arrowstyle='->',
                color='#666',
                lw=0.9,
                mutation_scale=10))

    ax.annotate(
        '', xy=(7.54, 0.42),
        xytext=(3.8, 0.42),
        arrowprops=dict(
            arrowstyle='<->',
            color='#1E7A4E',
            lw=0.7,
            mutation_scale=8))
    ax.text(5.67, 0.29,
            'pre-event window '
            '(20 turns before anchor)',
            ha='center', fontsize=6.5,
            color='#1E7A4E', style='italic')

    plt.tight_layout(pad=0.2)
    plt.savefig(save_path, dpi=300,
                bbox_inches='tight',
                facecolor='white')
    plt.close()
    print(f"Saved: {save_path}")


if __name__ == '__main__':
    create_pipeline_figure(
        '/content/drive/MyDrive/'
        'fig_pipeline.png')

# figures/fig_pipeline.py

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


def create_pipeline_figure(save_path):
    plt.rcParams.update({
        'font.family': 'serif',
        'mathtext.fontset': 'stix',
        'font.size': 9
    })

    fig, ax = plt.subplots(figsize=(7.2, 2.79))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 3)
    ax.axis('off')

    steps = [
        (0.1,  0.65, 1.55, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'Across\nDialogue\nDomains',
         '5 corpora (KO, EN)'),
        (1.95, 0.65, 1.55, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'LaBSE\nencoding',
         '768-dim utterances'),
        (3.8,  0.65, 1.55, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'Session-level\nPCA',
         '2D per session'),
        (5.65, 0.55, 1.9,  1.9,
         '#C5EAD8', '#1E7A4E', 1.5,
         'Lévy-area\ncomputation',
         r'$\mathrm{LA}(w)='
         r'\frac{1}{2}\sum_i'
         r'(x_i\Delta y_i-y_i\Delta x_i)$'),
        (7.85, 0.65, 2.05, 1.7,
         '#F2DFC0', '#8B6845', 1.0,
         'Archetype\ndiscovery',
         r'$k=4$, silhouette $=.400$'),
    ]

    for (x, y, w, h, fc, ec, lw,
         title, sub) in steps:
        ax.add_patch(mpatches.FancyBboxPatch(
            (x, y), w, h,
            boxstyle="round,pad=0.06",
            fc=fc, ec=ec, lw=lw, zorder=2))
        ax.text(x + w / 2, y + h * 0.63,
                title,
                ha='center', va='center',
                fontsize=8.5, fontweight='bold',
                color='#222222', zorder=3,
                multialignment='center')
        ax.text(x + w / 2, y + h * 0.24,
                sub,
                ha='center', va='center',
                fontsize=7, color='#555555',
                style='italic', zorder=3)

    for xa in [1.65, 3.5, 5.35, 7.55]:
        ax.annotate(
            '', xy=(xa + 0.25, 1.5),
            xytext=(xa, 1.5),
            arrowprops=dict(
                arrowstyle='->',
                color='#666',
                lw=0.9,
                mutation_scale=10))

    ax.annotate(
        '', xy=(7.54, 0.42),
        xytext=(3.8, 0.42),
        arrowprops=dict(
            arrowstyle='<->',
            color='#1E7A4E',
            lw=0.7,
            mutation_scale=8))
    ax.text(5.67, 0.29,
            'pre-event window '
            '(20 turns before anchor)',
            ha='center', fontsize=6.5,
            color='#1E7A4E', style='italic')

    plt.tight_layout(pad=0.2)
    plt.savefig(save_path, dpi=300,
                bbox_inches='tight',
                facecolor='white')
    plt.close()
    print(f"Saved: {save_path}")


if __name__ == '__main__':
    create_pipeline_figure(
        '/content/drive/MyDrive/'
        'fig_pipeline.png')