# -*- coding: utf-8 -*-
"""appendix_a1_cross_corpus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXrPD2nURNXa7nfFWtRoISVjEmMJ137_
"""

fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))
fig.suptitle(
    'Figure 3: Cross-Corpus Archetype Replication\n'
    '(Korean = solid; ESConv = dashed)',
    fontsize=12, fontweight='bold')

archetype_overlay = [
    ('Stable positive',  0, 3, '#1D9E75'),
    ('Negative drift',   1, 0, '#185FA5'),
    ('Positive surge',   3, 1, '#993C1D'),
]

x50 = np.linspace(0, 1, 50)

for col, (atype, ko_c, es_c, color) in \
        enumerate(archetype_overlay):
    ax = axes[col]

    # Korean curves
    ko_mask = labels4_clean == ko_c
    ko_sids = [pre_results_clean[i]['dialogue_id']
               for i in range(len(pre_results_clean))
               if ko_mask[i] and
               pre_results_clean[i]['dialogue_id']
               in korean_levy]
    ko_curves = [np.interp(x50,
                           np.linspace(0,1,
                           len(korean_levy[s])),
                           korean_levy[s])
                 for s in ko_sids]
    ko_mean = np.mean(ko_curves, axis=0)
    ko_std  = np.std(ko_curves,  axis=0)

    # ESConv curves
    es_sids = [sid for sid, lbl
               in es_sid_to_label.items()
               if lbl == es_c and sid in esconv_levy]
    es_curves = [np.interp(x50,
                           np.linspace(0,1,
                           len(esconv_levy[s])),
                           esconv_levy[s])
                 for s in es_sids]
    es_mean = np.mean(es_curves, axis=0)
    es_std  = np.std(es_curves,  axis=0)

    # Korean: solid
    ax.plot(x50, ko_mean, color=color,
            linewidth=2.5, linestyle='-',
            label=f'Korean (n={len(ko_curves)})',
            zorder=3)
    ax.fill_between(x50,
                    ko_mean - ko_std,
                    ko_mean + ko_std,
                    alpha=0.15, color=color)

    # ESConv: dashed
    ax.plot(x50, es_mean, color=color,
            linewidth=2.5, linestyle='--',
            label=f'ESConv (n={len(es_curves)})',
            zorder=3)
    ax.fill_between(x50,
                    es_mean - es_std,
                    es_mean + es_std,
                    alpha=0.08, color=color)

    ax.axhline(0, color='gray', linestyle=':',
               linewidth=0.8, alpha=0.6)
    ax.set_title(atype, fontsize=12,
                 color=color, fontweight='bold')
    ax.set_xlabel('Session progress', fontsize=10)
    if col == 0:
        ax.set_ylabel('Lévy area (z-scored)', fontsize=10)
    ax.legend(fontsize=8, loc='lower left')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.set_xlim(0, 1)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/figure3_replication.png",
            dpi=300, bbox_inches='tight')
plt.show()
print("저장 완료!")