# -*- coding: utf-8 -*-
"""appendix_a4_dendrogram

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxYGoju30NGkA5b6mvKxY4Rx0G4BknAQ
"""



import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score

plt.rcParams.update({'font.family':'serif',
                     'mathtext.fontset':'stix',
                     'font.size':10})

Z = linkage(X3_scaled, method='ward')

# GMM으로 BIC 기준 최적 k 선택 (본문 "BIC favours k=2" 주장 검증)
bic_scores = []
for k in range(2, 7):
    gmm_k = GaussianMixture(n_components=k, random_state=42, n_init=5)
    gmm_k.fit(X3_scaled)
    bic_scores.append(gmm_k.bic(X3_scaled))
best_k_bic = np.argmin(bic_scores) + 2
print(f"BIC-selected k: {best_k_bic} "
      f"(scores: {[f'{b:.1f}' for b in bic_scores]})")

gmm2 = GaussianMixture(n_components=2, random_state=42, n_init=10)
labels_gmm2 = gmm2.fit_predict(X3_scaled)

fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))

# ── Panel A: Dendrogram ──────────────────────────────────
ax = axes[0]
arch_colors = {0:'#5B9FD4', 1:'#C0392B',
               2:'#185FA5', 3:'#E8896A'}
dend = dendrogram(Z, ax=ax, no_labels=True,
                  color_threshold=0,
                  above_threshold_color='#AAAAAA')

heights = sorted(Z[:,2], reverse=True)
cut2 = (heights[1] + heights[2]) / 2
cut4 = (heights[3] + heights[4]) / 2
ax.axhline(cut2, color='#C0392B', linewidth=1.8,
           linestyle='--', label='k=2 cut', zorder=5)
ax.axhline(cut4, color='#1D9E75', linewidth=1.8,
           linestyle='--', label='k=4 cut', zorder=5)

leaf_order = dend['leaves']
n = len(leaf_order)
bar_w = (ax.get_xlim()[1]-ax.get_xlim()[0]) / n
for i, leaf_idx in enumerate(leaf_order):
    color = arch_colors[labels4_clean[leaf_idx]]
    ax.add_patch(plt.Rectangle(
        (ax.get_xlim()[0]+i*bar_w, -1.2),
        bar_w, 0.8, color=color, clip_on=False))

ax.set_title('(a) Hierarchical clustering\n(Ward linkage)',
             fontsize=11, fontweight='bold')
ax.set_xlabel('Sessions', fontsize=10)
ax.set_ylabel('Distance', fontsize=10)
ax.set_ylim(-1.5, None)
ax.legend(fontsize=9, loc='upper left')
ax.spines[['top','right','bottom']].set_visible(False)
ax.set_xticks([])

# ── Panel B: base vs pre scatter ─────────────────────────
ax2 = axes[1]
arch_labels = {0:'Stable +', 1:'Pos. surge',
               2:'Stable −', 3:'Neg. drift'}
markers4 = {0:'o', 1:'^', 2:'s', 3:'D'}

for g, fc in [(0,'#185FA5'), (1,'#C0392B')]:
    mask = labels_gmm2 == g
    ax2.scatter(X3_scaled[mask,0], X3_scaled[mask,1],
                c=fc, alpha=0.10, s=200,
                edgecolors='none', zorder=1)

for k in range(4):
    mask = labels4_clean == k
    ax2.scatter(X3_scaled[mask,0], X3_scaled[mask,1],
                c=arch_colors[k], marker=markers4[k],
                s=60, alpha=0.85,
                edgecolors='white', linewidths=0.6,
                label=f'Arch {k}: {arch_labels[k]} (n={mask.sum()})',
                zorder=3)

ax2.axvline(0, color='#ccc', linewidth=0.8,
            linestyle=':', zorder=0)
ax2.axhline(0, color='#ccc', linewidth=0.8,
            linestyle=':', zorder=0)
ax2.plot([-3,3],[-3,3], color='#ccc', linewidth=0.6,
         linestyle='-', alpha=0.5, zorder=0)
ax2.annotate('no change\n(base=pre)', xy=(1.7,1.7),
            fontsize=7.5, color='#999', rotation=45,
            ha='center')

ax2.set_xlabel('Baseline LA (z-scored)', fontsize=10)
ax2.set_ylabel('Pre-event LA (z-scored)', fontsize=10)
ax2.set_title('(b) Archetype structure\n'
              '(background = GMM k=2 groups, BIC-selected)',
              fontsize=11, fontweight='bold')
ax2.legend(fontsize=8, loc='lower right', framealpha=0.92)
ax2.spines[['top','right']].set_visible(False)

sil_gmm2 = silhouette_score(X3_scaled, labels_gmm2)
sil_km4 = silhouette_score(X3_scaled, labels4_clean)
ax2.text(0.03, 0.96,
         f'sil(k=2, GMM)={sil_gmm2:.3f}\nsil(k=4, k-means)={sil_km4:.3f}',
         transform=ax2.transAxes, ha='left', va='top',
         fontsize=8.5, color='#444',
         bbox=dict(boxstyle='round,pad=0.3',
                   fc='white', ec='#ccc', alpha=0.9))

plt.suptitle('Cluster structure of Lévy-area features\n'
             '(Korean corpus, N=70)',
             fontsize=11, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('fig_dendrogram_v2.png',
            dpi=300, bbox_inches='tight', facecolor='white')
plt.show()
print("✅ 완료")