# -*- coding: utf-8 -*-
"""appendix_a2_cluster_overlay.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WU2eNnt3sQ15qx4-QdCDcIEhZtyUepea
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

target_clusters = [1, 3]
titles = {
    1: f'Cluster 1 (N={sum(labels4_clean==1)})\nΔLA≈-0.82',
    3: f'Cluster 3 (N={sum(labels4_clean==3)})\nΔLA≈+1.02'
}

for ax, c in zip(axes, target_clusters):
    mask = labels4_clean == c
    c_sids = [pre_results_clean[i]['dialogue_id']
              for i in range(len(pre_results_clean)) if mask[i]]

    all_curves = []
    for sid in c_sids:
        la = bal_features[sid]['levy_area']
        la_mean, la_std = np.mean(la), np.std(la)
        if la_std < 1e-10:
            continue
        la_norm = (la - la_mean) / la_std
        x = np.linspace(0, 1, len(la_norm))
        ax.plot(x, la_norm, alpha=0.25, linewidth=1,
                color='steelblue' if c==1 else 'coral')
        # 보간해서 평균용으로 저장
        all_curves.append(np.interp(
            np.linspace(0, 1, 50),
            np.linspace(0, 1, len(la_norm)),
            la_norm
        ))

    # 평균 곡선
    if all_curves:
        mean_curve = np.mean(all_curves, axis=0)
        std_curve = np.std(all_curves, axis=0)
        x50 = np.linspace(0, 1, 50)
        ax.plot(x50, mean_curve, 'k-', linewidth=2.5, label='mean')
        ax.fill_between(x50,
                        mean_curve - std_curve,
                        mean_curve + std_curve,
                        alpha=0.15, color='black', label='±1 SD')

    ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)
    ax.set_title(titles[c], fontsize=12)
    ax.set_xlabel('Session progress (0=start, 1=end)')
    ax.set_ylabel('Levy Area (z-scored)')
    ax.legend(fontsize=9)

plt.suptitle('Cluster 1 vs Cluster 3: Individual + Mean Levy Area Curves',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/cluster1vs3_overlay.png",
            dpi=150, bbox_inches='tight')
plt.show()
print("저장 완료!")