# -*- coding: utf-8 -*-
"""appendix_a3_clinical

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWOahSlGcjVjxdKMN78OsEYq7Y1jmTrt
"""

# Figure 5: Clinical Relevance (ANNO-MI)
fig, axes = plt.subplots(1, 2, figsize=(9, 4.5))

archetypes = ['Archetype 0\n(convergent)',
              'Archetype 1\n(expanding)']
colors_arch = ['#185FA5', '#993C1D']

# Panel A: MI quality
ax = axes[0]
mi_quality = [96.8, 80.8]
bars = ax.bar(archetypes, mi_quality,
              color=colors_arch, width=0.5,
              alpha=0.85, edgecolor='white')
for bar, val in zip(bars, mi_quality):
    ax.text(bar.get_x() + bar.get_width()/2,
            val + 0.8, f'{val}%',
            ha='center', fontsize=11,
            fontweight='bold')
ax.set_ylim(0, 105)
ax.set_ylabel('High-fidelity MI sessions (%)',
              fontsize=10)
ax.set_title('(a) MI quality\n'
             '(OR = 7.14, p = 0.063)',
             fontsize=11)
ax.axhline(100, color='gray', linestyle=':',
           alpha=0.3)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel B: Complex reflection ratio
ax = axes[1]
cr_ratio = [0.528, 0.413]
bars = ax.bar(archetypes, cr_ratio,
              color=colors_arch, width=0.5,
              alpha=0.85, edgecolor='white')
for bar, val in zip(bars, cr_ratio):
    ax.text(bar.get_x() + bar.get_width()/2,
            val + 0.01, f'{val:.3f}',
            ha='center', fontsize=11,
            fontweight='bold')
ax.set_ylim(0, 0.65)
ax.set_ylabel('Complex reflection ratio',
              fontsize=10)
ax.set_title('(b) Complex reflection\n'
             '(Mann-Whitney p = 0.086)',
             fontsize=11)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.suptitle('Figure 5: Clinical Relevance — '
             'ANNO-MI Archetype Associations',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/fig4_clinical.png",
            dpi=300, bbox_inches='tight')
plt.show()
print("저장 완료!")