# -*- coding: utf-8 -*-
"""fig1_archetypes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMY5wrXhqizA43_CTWYqaMxpb7V0xrsd
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# ── PANEL A: Schematic - Why Lévy area? ──
ax = axes[0]
ax.set_aspect('equal')
ax.set_xlim(-0.55, 0.55)
ax.set_ylim(-0.48, 0.42)

# 같은 시작/끝점을 가진 두 개의 반원 호
# Path A: 위쪽 호 (CW, 음수 Lévy area)
theta_a = np.linspace(np.pi, 0, 100)
x_a = 0.3 * np.cos(theta_a)
y_a = 0.3 * np.sin(theta_a)

# Path B: 아래쪽 호 (CCW, 양수 Lévy area)
theta_b = np.linspace(np.pi, 2*np.pi, 100)
x_b = 0.3 * np.cos(theta_b)
y_b = 0.3 * np.sin(theta_b)

# 면적 음영
ax.fill_between(x_a, 0, y_a, where=(y_a >= 0),
                color='#E6F1FB', alpha=0.7, label='_nolegend_')
ax.fill_between(x_b, y_b, 0, where=(y_b <= 0),
                color='#FAECE7', alpha=0.7, label='_nolegend_')

# 호 그리기
ax.plot(x_a, y_a, color='#185FA5', linewidth=2.5, zorder=3)
ax.plot(x_b, y_b, color='#993C1D', linewidth=2.5, zorder=3)

# 방향 화살표 (중간 지점)
for mid, xs, ys, col in [
    (50, x_a, y_a, '#185FA5'),
    (50, x_b, y_b, '#993C1D')]:
    ax.annotate('',
        xy=(xs[mid+4], ys[mid+4]),
        xytext=(xs[mid], ys[mid]),
        arrowprops=dict(arrowstyle='->', color=col, lw=2.0,
                        mutation_scale=14))

# 시작/끝 마커
ax.scatter(-0.3, 0, c='#1D9E75', s=70, zorder=5, marker='o')
ax.scatter( 0.3, 0, c='#444441', s=70, zorder=5, marker='s')
ax.text(-0.3, 0.05, 'start', ha='center', fontsize=8, color='#1D9E75')
ax.text( 0.3, 0.05, 'end',   ha='center', fontsize=8, color='#444441')

# 면적 레이블
ax.text(0,  0.17, 'Lévy area < 0',
        ha='center', va='center', fontsize=9,
        color='#185FA5', fontweight='bold')
ax.text(0, -0.17, 'Lévy area > 0',
        ha='center', va='center', fontsize=9,
        color='#993C1D', fontweight='bold')

# 하단 설명
ax.text(0, -0.43,
        'Same endpoints · same path length\n→ different directional ordering',
        ha='center', va='center', fontsize=8,
        color='#5F5E5A', style='italic')

ax.axhline(0, color='#B4B2A9', linewidth=0.8,
           linestyle='--', alpha=0.7)
ax.set_xlabel('semantic dim 1 (PCA)', fontsize=10)
ax.set_ylabel('semantic dim 2 (PCA)', fontsize=10)
ax.set_title('(a) Why Lévy area?\nSame endpoints, different rotation',
             fontsize=11)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# ── PANEL B: 대표 세션 Lévy area profiles ──
ax = axes[1]

c1_indices = [i for i in range(len(pre_results_clean))
              if labels4_clean[i] == 1]
c3_indices = [i for i in range(len(pre_results_clean))
              if labels4_clean[i] == 3]
c1_dists = np.linalg.norm(
    X3_scaled[labels4_clean==1] - km4.cluster_centers_[1], axis=1)
sid_c1 = pre_results_clean[c1_indices[np.argmin(c1_dists)]]['dialogue_id']
c3_dists = np.linalg.norm(
    X3_scaled[labels4_clean==3] - km4.cluster_centers_[3], axis=1)
for idx in np.argsort(c3_dists):
    sid = pre_results_clean[c3_indices[idx]]['dialogue_id']
    if sid != 'A117':
        sid_c3 = sid
        break

for sid, color, cname, delta in [
    (sid_c1, '#185FA5', 'Cluster 1', '−0.82'),
    (sid_c3, '#993C1D', 'Cluster 3', '+1.02')]:
    la = bal_features[sid]['levy_area']
    la_std = np.std(la)
    if la_std < 1e-10: continue
    la_norm = (la - np.mean(la)) / la_std
    xp = np.linspace(0, 1, len(la_norm))
    ax.plot(xp, la_norm, color=color, linewidth=2,
            label=f'{cname} (Δ={delta})', alpha=0.9)
    ri = [i for i,r in enumerate(
          bal_features[sid]['risk_turns']) if r==1]
    if ri:
        pw = ri[0] // 10
        if pw < len(la_norm):
            ax.axvline(pw/len(la_norm), color=color,
                       linestyle=':', linewidth=1.5, alpha=0.6)

ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)
ax.text(0.98, 0.97, '⋮ anchor event', transform=ax.transAxes,
        fontsize=8, color='gray', va='top', ha='right')
ax.set_title('(b) Representative Lévy-area profiles\n(individual sessions)',
             fontsize=11)
ax.set_xlabel('Session progress', fontsize=10)
ax.set_ylabel('Lévy area (z-scored)', fontsize=10)
ax.legend(fontsize=9)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# ── PANEL C: 4-cluster archetypes ──
ax = axes[2]
colors_c = {0:'#888780', 1:'#185FA5', 2:'#D85A30', 3:'#993C1D'}
lws_c    = {0:1.2, 1:2.5, 2:1.2, 3:2.5}
alphas_c = {0:0.45, 1:1.0, 2:0.45, 3:1.0}
delta_c  = {0:'+0.03', 1:'−0.82', 2:'−0.03', 3:'+1.02'}

for c in range(4):
    mask   = labels4_clean == c
    c_sids = [pre_results_clean[i]['dialogue_id']
              for i in range(len(pre_results_clean)) if mask[i]]
    curves = []
    for sid in c_sids:
        la = bal_features[sid]['levy_area']
        ls = np.std(la)
        if ls < 1e-10: continue
        la_n = (la - np.mean(la)) / ls
        curves.append(np.interp(
            np.linspace(0,1,50),
            np.linspace(0,1,len(la_n)), la_n))
    if not curves: continue
    mc  = np.mean(curves, axis=0)
    sc  = np.std(curves,  axis=0)
    x50 = np.linspace(0, 1, 50)
    ax.plot(x50, mc, color=colors_c[c],
            linewidth=lws_c[c], alpha=alphas_c[c],
            label=f'C{c} (N={len(curves)}, Δ={delta_c[c]})')
    if c in [1, 3]:
        ax.fill_between(x50, mc-sc, mc+sc,
                        alpha=0.12, color=colors_c[c])

ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)
ax.set_title('(c) Cluster archetypes\n(mean ± SD, k=4)', fontsize=11)
ax.set_xlabel('Session progress', fontsize=10)
ax.set_ylabel('Lévy area (z-scored)', fontsize=10)
ax.legend(fontsize=8)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.suptitle(
    'Figure 1: Semantic Trajectory Archetypes in Counseling Discourse',
    fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/figure1_final.png",
            dpi=300, bbox_inches='tight')
plt.show()
print("저장 완료!")