# -*- coding: utf-8 -*-
"""fig_cmv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bERtiLsqrMd3JDhfddTloCx9pHqrd8pj
"""

# figures/fig_cmv.py

import numpy as np
import matplotlib.pyplot as plt


def create_cmv_figure(cmv_profiles,
                      surge_profiles,
                      save_path):
    """
    Args:
        cmv_profiles: dict with archetype
                      mean/std profiles for CMV
        surge_profiles: dict with positive surge
                        profiles per corpus
        save_path: output path
    """
    plt.rcParams.update({
        'font.family': 'serif',
        'mathtext.fontset': 'stix',
        'font.size': 9
    })

    fig, axes = plt.subplots(
        1, 2, figsize=(12, 4.5))

    colors = {
        'stable_neg': '#AAAAAA',
        'stable_pos': '#CCCCCC',
        'surge':      '#D85A30',
        'drift':      '#8B3A2A',
    }

    # Panel (a): CMV archetype profiles
    ax = axes[0]
    x = np.linspace(0, 1, 50)

    for archetype, color, label in [
        ('stable_neg', colors['stable_neg'],
         f'Stable $-$ (N=585, $\\Delta=-0.004$)'),
        ('stable_pos', colors['stable_pos'],
         f'Stable $+$ (N=428, $\\Delta=-0.057$)'),
        ('surge',      colors['surge'],
         f'Positive surge (N=396, $\\Delta=+1.022$)'),
        ('drift',      colors['drift'],
         f'Negative drift (N=350, $\\Delta=-1.072$)'),
    ]:
        mean = cmv_profiles[archetype]['mean']
        std  = cmv_profiles[archetype]['std']
        ax.plot(x, mean, color=color, lw=2)
        ax.fill_between(x,
                        mean - std,
                        mean + std,
                        alpha=0.15,
                        color=color)
        ax.plot([], [], color=color,
                lw=2, label=label)

    ax.axhline(0, color='gray',
               lw=0.8, linestyle='--',
               alpha=0.5)
    ax.set_xlabel('Session progress',
                  fontsize=9)
    ax.set_ylabel('Lévy area (z-scored)',
                  fontsize=9)
    ax.set_title(
        '(a) CMV archetype mean profiles\n'
        '($k=4$, $N=1,759$, '
        'sil$=.343$, $p<.0001$)',
        fontsize=10)
    ax.legend(fontsize=7.5, loc='lower left')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Panel (b): Positive surge comparison
    ax = axes[1]
    configs = [
        ('Korean',
         '#8B0000', '--',
         surge_profiles['korean'],
         r'Korean ($\Delta=+1.02$, $n=9$)'),
        ('ESConv',
         '#2E8B57', ':',
         surge_profiles['esconv'],
         r'ESConv ($\Delta=+0.34$, $n=9$)'),
        ('CMV',
         '#D85A30', '-',
         surge_profiles['cmv'],
         r'CMV ($\Delta=+1.022$, $N=396$)'),
    ]

    for name, color, ls, profile, label \
            in configs:
        mean = profile['mean']
        std  = profile['std']
        ax.plot(x, mean, color=color,
                lw=2, linestyle=ls,
                label=label)
        if name == 'CMV':
            ax.fill_between(
                x, mean - std, mean + std,
                alpha=0.15, color=color)

    ax.axhline(0, color='gray',
               lw=0.8, linestyle='--',
               alpha=0.5)
    ax.set_xlabel('Session progress',
                  fontsize=9)
    ax.set_ylabel('Lévy area (z-scored)',
                  fontsize=9)
    ax.set_title(
        '(b) Positive surge archetype:\n'
        'clinical · peer support · persuasion',
        fontsize=10)
    ax.legend(fontsize=8)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.suptitle(
        'Figure: Lévy-Area Trajectory '
        'Archetypes across Dialogue Domains',
        fontsize=11, fontweight='bold')
    plt.tight_layout()
    plt.savefig(save_path, dpi=300,
                bbox_inches='tight',
                facecolor='white')
    plt.close()
    print(f"Saved: {save_path}")
