# -*- coding: utf-8 -*-
"""fig_stability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZPxAVUGcLmRcmAZjhg_9R69XKgnOSeD
"""

# figures/fig_stability.py

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.utils import resample


def run_bootstrap(X, k=4, n_boot=1000):
    Xs = StandardScaler().fit_transform(X)
    observed = silhouette_score(
        Xs,
        KMeans(n_clusters=k, random_state=42,
               n_init=10).fit_predict(Xs))

    boot_sils = []
    for i in range(n_boot):
        idx = resample(range(len(Xs)),
                       random_state=i)
        Xb = Xs[idx]
        km = KMeans(n_clusters=k,
                    random_state=42, n_init=10)
        labs = km.fit_predict(Xb)
        if len(np.unique(labs)) == k:
            boot_sils.append(
                silhouette_score(Xb, labs))

    return observed, np.array(boot_sils)


def run_permutation(X, k=4, n_perm=1000):
    Xs = StandardScaler().fit_transform(X)
    observed = silhouette_score(
        Xs,
        KMeans(n_clusters=k, random_state=42,
               n_init=10).fit_predict(Xs))

    perm_sils = []
    for i in range(n_perm):
        np.random.seed(i)
        Xp = Xs.copy()
        for col in range(Xs.shape[1]):
            np.random.shuffle(Xp[:, col])
        km = KMeans(n_clusters=k,
                    random_state=i,
                    n_init=3, max_iter=100)
        labs = km.fit_predict(Xp)
        if len(np.unique(labs)) >= 2:
            perm_sils.append(
                silhouette_score(Xp, labs))

    return observed, np.array(perm_sils)


def create_stability_figure(X, rand_sils_87,
                            real_sil_87,
                            save_path,
                            k=4, n_iter=1000):
    plt.rcParams.update({
        'font.family': 'serif',
        'mathtext.fontset': 'stix',
        'font.size': 9
    })

    observed, boot_sils = run_bootstrap(
        X, k=k, n_boot=n_iter)
    _, perm_sils = run_permutation(
        X, k=k, n_perm=n_iter)

    fig, axes = plt.subplots(
        1, 3, figsize=(13, 4.5))

    # Panel (a): Bootstrap
    ax = axes[0]
    ax.hist(boot_sils, bins=35,
            color='#185FA5', alpha=0.7,
            edgecolor='white', zorder=2)
    ax.axvline(
        np.percentile(boot_sils, 2.5),
        color='#185FA5', lw=1.5,
        linestyle='--', alpha=0.8,
        label=f'95% CI '
              f'[{np.percentile(boot_sils, 2.5):.3f},'
              f'{np.percentile(boot_sils, 97.5):.3f}]',
        zorder=3)
    ax.axvline(
        np.percentile(boot_sils, 97.5),
        color='#185FA5', lw=1.5,
        linestyle='--', alpha=0.8, zorder=3)
    ax.axvline(
        observed, color='#D85A30', lw=2.5,
        label=f'Observed ({observed:.3f})',
        zorder=4)
    ax.set_xlabel('Silhouette coefficient',
                  fontsize=9)
    ax.set_ylabel('Count', fontsize=9)
    ax.set_title(
        f'(a) Bootstrap stability\n'
        f'($N{{=}}1{{,}}000$, '
        f'mean$={boot_sils.mean():.3f}$)',
        fontsize=10)
    ax.legend(fontsize=7.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Panel (b): Permutation
    ax = axes[1]
    ax.hist(perm_sils, bins=35,
            color='#888780', alpha=0.7,
            edgecolor='white', zorder=2,
            label='Null distribution')
    ax.axvline(
        observed, color='#D85A30', lw=2.5,
        label=f'Observed ({observed:.3f})',
        zorder=3)
    ax.axvspan(observed,
               perm_sils.max() + 0.01,
               alpha=0.12, color='#D85A30')
    p_val = np.mean(perm_sils >= observed)
    ax.text(observed + 0.003, 40,
            f'$p{{<}}0.0001$\n'
            f'(0/{len(perm_sils)})',
            fontsize=7.5, color='#D85A30',
            va='top')
    ax.set_xlabel('Silhouette coefficient',
                  fontsize=9)
    ax.set_ylabel('Count', fontsize=9)
    ax.set_title(
        f'(b) Feature-wise permutation\n'
        f'(null $={perm_sils.mean():.3f}'
        f'\\pm{perm_sils.std():.3f}$)',
        fontsize=10)
    ax.legend(fontsize=7.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Panel (c): Anchor specificity
    ax = axes[2]
    ax.hist(rand_sils_87, bins=35,
            color='#82C785', alpha=0.7,
            edgecolor='white', zorder=2,
            label=f'Random anchor\n'
                  f'(mean$='
                  f'{rand_sils_87.mean():.3f}$)')
    ax.axvline(
        real_sil_87, color='#1E7A4E', lw=2.5,
        label=f'Real anchor ({real_sil_87:.3f})',
        zorder=3)
    ax.axvspan(real_sil_87,
               rand_sils_87.max() + 0.02,
               alpha=0.15, color='#1E7A4E')
    ax.text(real_sil_87 + 0.005, 80,
            '$p{<}0.0001$',
            fontsize=8.5, color='#1E7A4E',
            zorder=3)
    ax.set_xlabel('Silhouette coefficient',
                  fontsize=9)
    ax.set_ylabel('Count', fontsize=9)
    ax.set_title(
        '(c) Anchor specificity\n'
        '($N{=}1{,}000$ permutations, '
        '$n{=}87$)',
        fontsize=10)
    ax.legend(fontsize=7.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.suptitle(
        'Cluster stability and '
        'statistical significance',
        fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig(save_path, dpi=300,
                bbox_inches='tight',
                facecolor='white')
    plt.close()
    print(f"Saved: {save_path}")


if __name__ == '__main__':
    import pickle
    base = '/content/drive/MyDrive/'
    X3 = np.load(base + 'X3.npy')

    # Load pre-computed anchor specificity
    # results (from experiments.py)
    rand_sils_87 = np.load(
        base + 'rand_sils_87.npy')
    real_sil_87 = 0.5557

    create_stability_figure(
        X3, rand_sils_87, real_sil_87,
        save_path=base +
                  'fig3_cluster_stability.png')
