# -*- coding: utf-8 -*-
"""src/clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzhoZNzD2LblKXU3YOV96P39WFXlgDX2
"""

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


def find_best_k(X, k_range=range(2, 7),
                n_init=10, random_state=42):
    """
    Find optimal k by maximising silhouette score.

    Returns:
        best_k, best_sil, all_scores dict
    """
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    scores = {}
    for k in k_range:
        km = KMeans(n_clusters=k,
                    n_init=n_init,
                    random_state=random_state)
        labels = km.fit_predict(Xs)
        if len(np.unique(labels)) >= 2:
            scores[k] = silhouette_score(Xs, labels)

    best_k = max(scores, key=scores.get)
    return best_k, scores[best_k], scores


def cluster_at_k(X, k=4, n_init=10,
                 random_state=42):
    """
    Cluster at specified k and return labels,
    silhouette, and archetype profiles.
    """
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    km = KMeans(n_clusters=k,
                n_init=n_init,
                random_state=random_state)
    labels = km.fit_predict(Xs)
    sil = silhouette_score(Xs, labels)

    profiles = {}
    for c in range(k):
        mask = labels == c
        profiles[c] = {
            'n': mask.sum(),
            'base': X[mask, 0].mean(),
            'pre': X[mask, 1].mean(),
            'delta': X[mask, 2].mean()
        }

    return labels, sil, profiles


def permutation_test(X, k=4, n_perm=1000,
                     observed_sil=None,
                     random_state=42):
    """
    Feature-wise permutation test.
    Independently shuffle each feature column.
    """
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    if observed_sil is None:
        km = KMeans(n_clusters=k, n_init=10,
                    random_state=random_state)
        observed_sil = silhouette_score(
            Xs, km.fit_predict(Xs))

    perm_sils = []
    for i in range(n_perm):
        np.random.seed(i)
        Xp = Xs.copy()
        for col in range(Xs.shape[1]):
            np.random.shuffle(Xp[:, col])
        km = KMeans(n_clusters=k, n_init=3,
                    max_iter=100,
                    random_state=i)
        labels = km.fit_predict(Xp)
        if len(np.unique(labels)) >= 2:
            perm_sils.append(
                silhouette_score(Xp, labels))

    perm_sils = np.array(perm_sils)
    p_val = np.mean(perm_sils >= observed_sil)

    return {
        'observed': observed_sil,
        'null_mean': perm_sils.mean(),
        'null_std': perm_sils.std(),
        'p_value': p_val,
        'null_distribution': perm_sils
    }


def bootstrap_stability(X, k=4,
                        n_boot=1000,
                        random_state=42):
    """
    Bootstrap stability analysis.
    """
    from sklearn.utils import resample

    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    boot_sils = []
    for i in range(n_boot):
        idx = resample(range(len(Xs)),
                       random_state=i)
        Xb = Xs[idx]
        km = KMeans(n_clusters=k, n_init=10,
                    random_state=42)
        labels = km.fit_predict(Xb)
        if len(np.unique(labels)) == k:
            boot_sils.append(
                silhouette_score(Xb, labels))

    boot_sils = np.array(boot_sils)
    return {
        'mean': boot_sils.mean(),
        'ci_lower': np.percentile(boot_sils, 2.5),
        'ci_upper': np.percentile(boot_sils, 97.5),
        'distribution': boot_sils
    }
