# -*- coding: utf-8 -*-
"""src/levy_area.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1m06ZbLdO53KIt-SluJ3rUTWfihmqRT
"""

import numpy as np
from sklearn.decomposition import PCA
from scipy.stats import zscore


def compute_levy_area(coords):
    """
    Compute Lévy area for 2D trajectory.
    LA = 0.5 * sum(x_i * dy_i - y_i * dx_i)
    """
    x, y = coords[:, 0], coords[:, 1]
    dx = np.diff(x)
    dy = np.diff(y)
    return 0.5 * np.sum(x[:-1] * dy - y[:-1] * dx)


def sliding_window_levy(embeddings,
                        window=20,
                        step=10,
                        n_components=2):
    """
    Compute sliding-window Lévy area sequence
    from utterance embeddings.

    Args:
        embeddings: (N, 768) LaBSE embeddings
        window: window size in turns
        step: step size
        n_components: PCA dimensions

    Returns:
        levy_sequence: array of Lévy area values
        or None if insufficient turns
    """
    if len(embeddings) < window:
        return None

    # Session-level PCA
    pca = PCA(n_components=n_components)
    coords = pca.fit_transform(embeddings)

    # Z-score per dimension
    for i in range(n_components):
        std = np.std(coords[:, i])
        if std > 1e-10:
            coords[:, i] = zscore(coords[:, i])

    # Sliding window
    levy_seq = []
    for start in range(0,
                       len(coords) - window + 1,
                       step):
        window_coords = coords[start:start + window]
        la = compute_levy_area(window_coords)
        levy_seq.append(la)

    return np.array(levy_seq) if len(levy_seq) >= 3 \
        else None


def extract_features(levy_seq, anchor_window):
    """
    Extract [base, pre, delta] features.

    Args:
        levy_seq: Lévy area sequence
        anchor_window: window index of anchor event

    Returns:
        [base_mean, pre_mean, delta] or None
    """
    if levy_seq is None or anchor_window < 3:
        return None

    la = levy_seq.copy()
    std = np.std(la)
    if std < 1e-10:
        return None
    la = (la - np.mean(la)) / std

    base = np.mean(la[:3])
    pre_start = max(0, anchor_window - 3)
    pre = np.mean(la[pre_start:anchor_window])

    return [base, pre, pre - base]
